import { Injectable } from '@angular/core';

@Injectable()
export class QuotesService {
    private trumpQuotes: Array<string> = ["The beauty of me is that I’m very rich.",
        "We need global warming!",
        "I have never seen a thin person drinking Diet Coke.",
        "I’m more honest and my women are more beautiful.",
        "You’re disgusting.",
        "The point is, you can never be too greedy.",
        "I can actually make my enemies tell the truth.",
        "My IQ is one of the highest — and you all know it!",
        "Please don’t feel so stupid or insecure; it’s not your fault.",
        "Look at those hands, are they small hands?",
        "If they’re small, something else must be small.’ I guarantee you there’s no problem. I guarantee.",
        "It really doesn’t matter what the media write as long as you’ve got a young, and beautiful, piece of ass.",
        "I will build a great wall – and nobody builds walls better than me, believe me.",
        "I will make Mexico pay for that wall. Mark my words.",
        "A person who is very flat-chested is very hard to be a 10.",
        "When I come home and dinner’s not ready, I go through the roof.",
        "Sadly, she’s no longer a 10.",
        "I like kids. I mean, I won’t do anything to take care of ’em.",
        "Look at that face! Would anyone vote for that?",
        "She’s a woman, and I’m not supposed to say bad things, but really, folks, come on.",
        "So this is somebody that likes to eat.",
        "She gained a massive amount of weight, and it was a real problem.",
        "I’d like to take some money out of her fatass pockets.",
        "You take a look at her, she’s a slob.",
        "She talks like a—like a truck driver.",
        "The boob job is terrible. They look like two lightbulbs coming out of her body.",
        "The face of a dog!",
        "Don’t you think my daughter’s hot? She’s hot, right?",
        "Wow! Just think—in a couple of years I’ll be dating you.",
        "I’d say she’s a solid nine, solid nine, yeah.",
        "I just start kissing them. It’s like a magnet. Just kiss.",
        "When you’re a star, they let you do it. You can do anything.",
        "Grab ’em by the P…",
        "Bimbo",
        "Why does she keep interrupting everybody?",
        "She doesn’t have the look. She doesn’t have the stamina.",
        "Third-rate",
        "You don’t know what you’re talking about. Try getting it out. Go ahead.",
        "Lightweight.",
        "Well, let’s say that there are better. By large margins.",
        "It’s fun, it’s kidding, we have a good time.",
        "Turned out to be a total lie.",
        "Loves to lie",
        "You have failed, failed, and failed.",
        "Zero imagination and even less stamina.",
        "Waste of time",
        "The man who ‘choked’ and let us all down.",
        "A total joke, and everyone knows it!",
        "Dummy",
        "Couldn't get elected dog catcher.",
        "Not a nice person!",
        "Highly overrated",
        "So average in so many ways!",
        "Doing many bad things behind our backs.",
        "Losers",
        "Mere puppets",
        "A total meltdown",
        "Credibility will soon be gone!",
        "They don't have a clue!",
        "Ratings are so low - and getting worse.",
        "So negative, getting even worse.",
        "Without me they'd have no ratings!",
        "A total disaster",
        "Rigged",
        "Totally rigged & corrupt!",
        "Disgrace",
        "Very dishonest",
        "A total waste of time",
        "A joke!",
        "A toy by comparison",
        "Will lead to at least partial world destruction",
        "One of the most incompetent ever made",
        "Totally distort so many things on purpose",
        "Very bad", "really bad",
        "Obsolete",
        "false and fictitious",
        "Very unfair!",
    ]

    getTrumpQuote(): string {
        return this.trumpQuotes[Math.floor(Math.random() * this.trumpQuotes.length)];
    }
}