import { Injectable } from '@angular/core';

@Injectable()
export class QuotesService {
    private trumpQuotes: Array<string> = [
        "The beauty of me is that I’m very rich.",
        "We need global warming!",
        "I have never seen a thin person drinking Diet Coke.",
        "I’m more honest and my women are more beautiful.",
        "You’re disgusting.",
        "The point is, you can never be too greedy.",
        "I can actually make my enemies tell the truth.",
        "My IQ is one of the highest — and you all know it!",
        "Please don’t feel so stupid or insecure; it’s not your fault.",
        "Look at those hands, are they small hands?",
        "I will build a great wall – and nobody builds walls better than me, believe me.",
        "A person who is very flat-chested is very hard to be a 10.",
        "Sadly, she’s no longer a 10.",
        "I like kids. I mean, I won’t do anything to take care of ’em.",
        "So this is somebody that likes to eat.",
        "Lightweight.",
        "Well, let’s say that there are better. By large margins.",
        "It’s fun, it’s kidding, we have a good time.",
        "Turned out to be a total lie.",
        "Loves to lie",
        "You have failed, failed, and failed.",
        "Zero imagination and even less stamina.",
        "Waste of time",
        "The man who ‘choked’ and let us all down.",
        "A total joke, and everyone knows it!",
        "Dummy",
        "Couldn't get elected dog catcher.",
        "Not a nice person!",
        "Highly overrated",
        "So average in so many ways!",
        "Doing many bad things behind our backs.",
        "Losers",
        "Mere puppets",
        "A total meltdown",
        "Credibility will soon be gone!",
        "They don't have a clue!",
        "Ratings are so low - and getting worse.",
        "So negative, getting even worse.",
        "Without me they'd have no ratings!",
        "A total disaster",
        "Rigged",
        "Totally rigged & corrupt!",
        "Disgrace",
        "Very dishonest",
        "A total waste of time",
        "A joke!",
        "A toy by comparison",
        "Will lead to at least partial world destruction",
        "One of the most incompetent ever made",
        "Totally distort so many things on purpose",
        "Very bad", "really bad",
        "Obsolete",
        "false and fictitious",
        "Very unfair!",
    ]

    getTrumpQuote(): string {
        return this.trumpQuotes[Math.floor(Math.random() * this.trumpQuotes.length)];
    }
}