# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.13.0"

default_platform :ios

platform :ios do
  desc "Compile a new build for for appstore"
  lane :release do
    app_name_sanitized = 'Facts'
    ios_project_path = "platforms/ios/#{app_name_sanitized}.xcodeproj"
    app_identifier = "com.simpleproductionsinc.alternativefacts"

    # Compile the ionic app
    sh("npm run ionic:release:build:ipa")
    # Get certificate
    cert
    # Get provisioning profile
    sigh(
      force: false
    )
    # Recreate schemes to ensure a smooth transition from cordova to gym
    recreate_schemes(
      project: ios_project_path
    )
    # Archive app into ipa
    gym(
      scheme: app_name_sanitized,
      project: ios_project_path,
      export_method: 'app-store'
    )
  end
end